# Site Information
title: Talljack
description: "Hi, I'm Talljack, a Frontend Engineer from China, also dabbling a bit in Swift, Rust, Go, React. Believing in long-termism, I am passionate about open source and enjoy experimenting with new ideas."
url: https://yugangcao.com
repo: Talljack/blog
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: Talljack
zhihu: Talljack
twitter: Yugangcao
# v2ex: Talljack
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about"
  - title: "Github"
    url: "https://github.com/Talljack"
  - title: "RSS"
    url: "/feed.xml"

# SEO and Analytics
google_analytics: G-KS7EDB6BRM

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: //gw.alipayobjects.com/zos/k/vb/1.png
assetUrl: //yugangcao.com/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
